% batch_visual_soccer.m
% visualization script for soccer erp data
% author: marlene buch
% date: 2025-10-15

%% paths
diffWaves = "C:\Users\localadmin\Documents\08_SocCEr\soccer-alpha\derivatives\2025-10-14_erp-postprocessing\difference_waves";
grandAver = "C:\Users\localadmin\Documents\08_SocCEr\soccer-alpha\derivatives\2025-10-14_erp-postprocessing\grand_averages";

%% color definitions
schwarz = [0 0 0];
grau = [105 105 105];

% visible conditions
vis_cor = [0 140 210];    % blue
vis_err = [210 85 40];     % main orange
vis_FE = [230 110 60];     % lighter orange
vis_NFE = [180 65 30];     % darker orange

% invisible conditions  
invis_NFG = [140 160 50];  % green/olive
invis_FE = [230 110 60];   % same as vis_FE

%% electrode clusters
ern_cluster = {'FCz', 'FC1', 'FC2'};
pe_cluster = {'CPz', 'CP1', 'CP2'};

%% ========================================================================
%% VISIBLE CONDITION - CORRECT VS ERROR (COLLAPSED)
%% ========================================================================

% grand averages - correct vs error collapsed
visual_comperp({'grandAVG_111_social-vis-corr', 'grandAVG_211_nonsoc-vis-corr', ...
                'diffWave_soc_vis_FE', 'diffWave_nonsoc_vis_FE'}, ...  % using diff waves for errors
                grandAver, 'electrodeCluster', ern_cluster);
pimpfigure('ERP', [-200 600 -8 6], {'1' '1:' '2' '2:'}, ...
           {'Social Correct', 'Nonsocial Correct', 'Social Error', 'Nonsocial Error'}, ...
           [0 100], [vis_cor; vis_err]);  % ERN window

visual_comperp({'grandAVG_111_social-vis-corr', 'grandAVG_211_nonsoc-vis-corr', ...
                'diffWave_soc_vis_FE', 'diffWave_nonsoc_vis_FE'}, ...
                grandAver, 'electrodeCluster', pe_cluster);
pimpfigure('ERP', [-200 600 -2 10], {'1' '1:' '2' '2:'}, ...
           {'Social Correct', 'Nonsocial Correct', 'Social Error', 'Nonsocial Error'}, ...
           [200 500], [vis_cor; vis_err]);  % Pe window

%% ========================================================================
%% VISIBLE CONDITION - ERROR TYPES
%% ========================================================================

% flanker vs non-flanker errors
visual_comperp({'diffWave_soc_vis_FE', 'diffWave_nonsoc_vis_FE', ...
                'diffWave_soc_vis_NFE', 'diffWave_nonsoc_vis_NFE'}, ...
                diffWaves, 'electrodeCluster', ern_cluster);
pimpfigure('ERP', [-200 600 -6 4], {'1' '1:' '2' '2:'}, ...
           {'Social FE', 'Nonsocial FE', 'Social NFE', 'Nonsocial NFE'}, ...
           [0 100], [vis_FE; vis_NFE]);  % ERN

visual_comperp({'diffWave_soc_vis_FE', 'diffWave_nonsoc_vis_FE', ...
                'diffWave_soc_vis_NFE', 'diffWave_nonsoc_vis_NFE'}, ...
                diffWaves, 'electrodeCluster', pe_cluster);
pimpfigure('ERP', [-200 600 -2 8], {'1' '1:' '2' '2:'}, ...
           {'Social FE', 'Nonsocial FE', 'Social NFE', 'Nonsocial NFE'}, ...
           [200 500], [vis_FE; vis_NFE]);  % Pe

% topoplots for visible error types
visual_topoplot({'diffWave_soc_vis_FE', 'diffWave_nonsoc_vis_FE'}, diffWaves, 50, [-5 5], 'mean', 50);  % ERN at 50ms
visual_topoplot({'diffWave_soc_vis_FE', 'diffWave_nonsoc_vis_FE'}, diffWaves, 350, [-4 4], 'mean', 350); % Pe at 350ms

%% ========================================================================
%% INVISIBLE CONDITION 
%% ========================================================================

% flanker error vs non-flanker guess
visual_comperp({'diffWave_soc_invis_FE', 'diffWave_nonsoc_invis_FE', ...
                'diffWave_soc_invis_NFG', 'diffWave_nonsoc_invis_NFG'}, ...
                diffWaves, 'electrodeCluster', ern_cluster);
pimpfigure('ERP', [-200 600 -6 4], {'1' '1:' '2' '2:'}, ...
           {'Social FE', 'Nonsocial FE', 'Social NFG', 'Nonsocial NFG'}, ...
           [0 100], [invis_FE; invis_NFG]);  % ERN

visual_comperp({'diffWave_soc_invis_FE', 'diffWave_nonsoc_invis_FE', ...
                'diffWave_soc_invis_NFG', 'diffWave_nonsoc_invis_NFG'}, ...
                diffWaves, 'electrodeCluster', pe_cluster);
pimpfigure('ERP', [-200 600 -2 8], {'1' '1:' '2' '2:'}, ...
           {'Social FE', 'Nonsocial FE', 'Social NFG', 'Nonsocial NFG'}, ...
           [200 500], [invis_FE; invis_NFG]);  % Pe

%% ========================================================================
%% CROSS-CONDITION COMPARISON - FLANKER ERRORS
%% ========================================================================

% compare flanker errors across visible and invisible
visual_comperp({'diffWave_soc_vis_FE', 'diffWave_nonsoc_vis_FE', ...
                'diffWave_soc_invis_FE', 'diffWave_nonsoc_invis_FE'}, ...
                diffWaves, 'electrodeCluster', ern_cluster);
pimpfigure('ERP', [-200 600 -6 4], {'1' '1:' '1-' '1:-'}, ...
           {'Social Visible FE', 'Nonsocial Visible FE', 'Social Invisible FE', 'Nonsocial Invisible FE'}, ...
           [0 100], [vis_FE; vis_FE]);  % same color, different line styles

%% ========================================================================
%% STATISTICAL ANALYSES
%% ========================================================================

%% VISIBLE CONDITION ANOVAS

% ERN - visible error types
design = table({'FE'; 'FE'; 'NFE'; 'NFE'}, ...
              {'social'; 'nonsocial'; 'social'; 'nonsocial'}, ...
              'VariableNames', {'ErrorType', 'SocialCondition'});
testing_meanAmplitude(diffWaves, ...
    {'diffWave_soc_vis_FE', 'diffWave_nonsoc_vis_FE', 'diffWave_soc_vis_NFE', 'diffWave_nonsoc_vis_NFE'}, ...
    {'Soc_FE', 'Nonsoc_FE', 'Soc_NFE', 'Nonsoc_NFE'}, ...
    'visible_ERN_output.txt', [0 100], ern_cluster, ...
    'ranova', design);

% Pe - visible error types  
testing_meanAmplitude(diffWaves, ...
    {'diffWave_soc_vis_FE', 'diffWave_nonsoc_vis_FE', 'diffWave_soc_vis_NFE', 'diffWave_nonsoc_vis_NFE'}, ...
    {'Soc_FE', 'Nonsoc_FE', 'Soc_NFE', 'Nonsoc_NFE'}, ...
    'visible_Pe_output.txt', [200 500], pe_cluster, ...
    'ranova', design);

%% INVISIBLE CONDITION ANOVAS

% ERN - invisible response types
design = table({'FE'; 'FE'; 'NFG'; 'NFG'}, ...
              {'social'; 'nonsocial'; 'social'; 'nonsocial'}, ...
              'VariableNames', {'ResponseType', 'SocialCondition'});
testing_meanAmplitude(diffWaves, ...
    {'diffWave_soc_invis_FE', 'diffWave_nonsoc_invis_FE', 'diffWave_soc_invis_NFG', 'diffWave_nonsoc_invis_NFG'}, ...
    {'Soc_FE', 'Nonsoc_FE', 'Soc_NFG', 'Nonsoc_NFG'}, ...
    'invisible_ERN_output.txt', [0 100], ern_cluster, ...
    'ranova', design);

% Pe - invisible response types
testing_meanAmplitude(diffWaves, ...
    {'diffWave_soc_invis_FE', 'diffWave_nonsoc_invis_FE', 'diffWave_soc_invis_NFG', 'diffWave_nonsoc_invis_NFG'}, ...
    {'Soc_FE', 'Nonsoc_FE', 'Soc_NFG', 'Nonsoc_NFG'}, ...
    'invisible_Pe_output.txt', [200 500], pe_cluster, ...
    'ranova', design);