% batch_erp_analyses.m
% statistical analyses script for soccer erp data
% author: marlene buch
% date: 2025-10-15

%% create timestamped output directory structure
timestamp = datestr(now, 'yyyy-mm-dd_HH-MM-SS');
resultsBase = 'C:\Users\localadmin\Documents\08_SocCEr\soccer-alpha\results\erp';
outputDir = fullfile(resultsBase, ['erp_' timestamp]);

% create subdirectories matching your existing structure
tablesDir = fullfile(outputDir, 'tables');
logsDir = fullfile(outputDir, 'logs');
reportsDir = fullfile(outputDir, 'reports');

if ~exist(tablesDir, 'dir'), mkdir(tablesDir); end
if ~exist(logsDir, 'dir'), mkdir(logsDir); end  
if ~exist(reportsDir, 'dir'), mkdir(reportsDir); end

% create separate folders for visible & invisible statistics
visTableDir = fullfile(tablesDir, 'visible-target');
invisTableDir = fullfile(tablesDir, 'invisible-target');
if ~exist(visTableDir, 'dir'), mkdir(visTableDir); end
if ~exist(invisTableDir, 'dir'), mkdir(invisTableDir); end

%% paths to data
diffWaves = "C:\Users\localadmin\Documents\08_SocCEr\soccer-alpha\derivatives\2025-10-15_erp-postprocessing\difference_waves";
grandAver = "C:\Users\localadmin\Documents\08_SocCEr\soccer-alpha\derivatives\2025-10-15_erp-postprocessing\grand_averages";

%% electrode clusters
ern_cluster = [1, 2, 34];
pe_cluster = [17, 18, 49];

%% start logging
diary(fullfile(logsDir, sprintf('erp_analysis_%s.log', timestamp)));
diary on;

fprintf('ERP Analysis Started: %s\n\n', timestamp);

%% ========================================================================
%% VISIBLE-TARGET
%% ========================================================================
fprintf('=== VISIBLE-TARGET ANALYSES ===\n\n');

%% ERN - test if detectable
% social-FE
testing_meanAmplitude(char(grandAver), ...
    {'grandAVG_112_social_vis_FE', 'grandAVG_111_social_vis_corr'}, ...
    {'Soc_FE', 'Soc_Corr'}, ...
    'visible_soc_FE_ERN_detection', [0 100], ern_cluster);

% social-NFE
testing_meanAmplitude(char(grandAver), ...
    {'grandAVG_113_social_vis_NFE', 'grandAVG_111_social_vis_corr'}, ...
    {'Soc_NFE', 'Soc_Corr'}, ...
    'visible_soc_NFE_ERN_detection', [0 100], ern_cluster);

% nonsocial-FE
testing_meanAmplitude(char(grandAver), ...
    {'grandAVG_212_nonsoc_vis_FE', 'grandAVG_211_nonsoc_vis_corr'}, ...
    {'Nonsoc_FE', 'Nonsoc_Corr'}, ...
    'visible_nonsoc_FE_ERN_detection', [0 100], ern_cluster);

% nonsocial-NFE
testing_meanAmplitude(char(grandAver), ...
    {'grandAVG_213_nonsoc_vis_NFE', 'grandAVG_211_nonsoc_vis_corr'}, ...
    {'Nonsoc_NFE', 'Nonsoc_Corr'}, ...
    'visible_nonsoc_NFE_ERN_detection', [0 100], ern_cluster);

%% delta-ERN ANOVA (error type × social condition)
design = table({'FE'; 'FE'; 'NFE'; 'NFE'}, ...
    {'social'; 'nonsocial'; 'social'; 'nonsocial'}, ...
    'VariableNames', {'ErrorType', 'SocialCondition'});
testing_meanAmplitude(char(diffWaves), ...
    {'diffWave_soc_vis_FE', 'diffWave_nonsoc_vis_FE', ...
     'diffWave_soc_vis_NFE', 'diffWave_nonsoc_vis_NFE'}, ...
    {'Soc_FE', 'Nonsoc_FE', 'Soc_NFE', 'Nonsoc_NFE'}, ...
    'visible_deltaERN_ANOVA', [0 100], ern_cluster, ...
    'ranova', design);

%% Pe - test if detectable
% social-FE
testing_meanAmplitude(char(grandAver), ...
    {'grandAVG_112_social_vis_FE', 'grandAVG_111_social_vis_corr'}, ...
    {'Soc_FE', 'Soc_Corr'}, ...
    'visible_soc_FE_Pe_detection', [200 500], pe_cluster);

% social-NFE
testing_meanAmplitude(char(grandAver), ...
    {'grandAVG_113_social_vis_NFE', 'grandAVG_111_social_vis_corr'}, ...
    {'Soc_NFE', 'Soc_Corr'}, ...
    'visible_soc_NFE_Pe_detection', [200 500], pe_cluster);

% nonsocial-FE
testing_meanAmplitude(char(grandAver), ...
    {'grandAVG_212_nonsoc_vis_FE', 'grandAVG_211_nonsoc_vis_corr'}, ...
    {'Nonsoc_FE', 'Nonsoc_Corr'}, ...
    'visible_nonsoc_FE_Pe_detection', [200 500], pe_cluster);

% nonsocial-NFE
testing_meanAmplitude(char(grandAver), ...
    {'grandAVG_213_nonsoc_vis_NFE', 'grandAVG_211_nonsoc_vis_corr'}, ...
    {'Nonsoc_NFE', 'Nonsoc_Corr'}, ...
    'visible_nonsoc_NFE_Pe_detection', [200 500], pe_cluster);

%% delta-Pe ANOVA (error type × social condition)
testing_meanAmplitude(char(diffWaves), ...
    {'diffWave_soc_vis_FE', 'diffWave_nonsoc_vis_FE', ...
     'diffWave_soc_vis_NFE', 'diffWave_nonsoc_vis_NFE'}, ...
    {'Soc_FE', 'Nonsoc_FE', 'Soc_NFE', 'Nonsoc_NFE'}, ...
    'visible_deltaPe_ANOVA', [200 500], pe_cluster, ...
    'ranova', design);

%% Additional tests - collapsed errors (FE + NFE combined)
fprintf('\n--- Collapsed Errors Analysis ---\n');

%% ERN - collapsed errors
% social collapsed errors
testing_meanAmplitude(char(grandAver), ...
    {'grandAVG_110_social_vis_error', 'grandAVG_111_social_vis_corr'}, ...
    {'Soc_Error_Collapsed', 'Soc_Corr'}, ...
    'visible_soc_collapsed_ERN_detection', [0 100], ern_cluster);

% nonsocial collapsed errors
testing_meanAmplitude(char(grandAver), ...
    {'grandAVG_210_nonsoc_vis_error', 'grandAVG_211_nonsoc_vis_corr'}, ...
    {'Nonsoc_Error_Collapsed', 'Nonsoc_Corr'}, ...
    'visible_nonsoc_collapsed_ERN_detection', [0 100], ern_cluster);

% delta-ERN t-test (social vs nonsocial)
testing_meanAmplitude(char(diffWaves), ...
    {'diffWave_soc_vis_error', 'diffWave_nonsoc_vis_error'}, ...
    {'Soc_Error_Collapsed', 'Nonsoc_Error_Collapsed'}, ...
    'visible_collapsed_deltaERN_comparison', [0 100], ern_cluster);

%% Pe - collapsed errors
% social collapsed errors
testing_meanAmplitude(char(grandAver), ...
    {'grandAVG_110_social_vis_error', 'grandAVG_111_social_vis_corr'}, ...
    {'Soc_Error_Collapsed', 'Soc_Corr'}, ...
    'visible_soc_collapsed_Pe_detection', [200 500], pe_cluster);

% nonsocial collapsed errors p = 0.033 → DETECTABLE
testing_meanAmplitude(char(grandAver), ...
    {'grandAVG_210_nonsoc_vis_error', 'grandAVG_211_nonsoc_vis_corr'}, ...
    {'Nonsoc_Error_Collapsed', 'Nonsoc_Corr'}, ...
    'visible_nonsoc_collapsed_Pe_detection', [200 500], pe_cluster);

% delta-Pe t-test (social vs nonsocial) → not significant: p = .782
testing_meanAmplitude(char(diffWaves), ...
    {'diffWave_soc_vis_error', 'diffWave_nonsoc_vis_error'}, ...
    {'Soc_Error_Collapsed', 'Nonsoc_Error_Collapsed'}, ...
    'visible_collapsed_deltaPe_comparison', [200 500], pe_cluster);

%% ========================================================================
%% INVISIBLE-TARGET
%% ========================================================================
fprintf('\n=== INVISIBLE-TARGET ANALYSES ===\n\n');

%% ERN - test if detectable
% social-FE
testing_meanAmplitude(char(grandAver), ...
    {'grandAVG_102_social_invis_FE', 'grandAVG_111_social_vis_corr'}, ...
    {'Soc_Invis_FE', 'Soc_Vis_Corr'}, ...
    'invisible_soc_FE_ERN_detection', [0 100], ern_cluster);

% social-NFG
testing_meanAmplitude(char(grandAver), ...
    {'grandAVG_104_social_invis_NFG', 'grandAVG_111_social_vis_corr'}, ...
    {'Soc_Invis_NFG', 'Soc_Vis_Corr'}, ...
    'invisible_soc_NFG_ERN_detection', [0 100], ern_cluster);

% nonsocial-FE
testing_meanAmplitude(char(grandAver), ...
    {'grandAVG_202_nonsoc_invis_FE', 'grandAVG_211_nonsoc_vis_corr'}, ...
    {'Nonsoc_Invis_FE', 'Nonsoc_Vis_Corr'}, ...
    'invisible_nonsoc_FE_ERN_detection', [0 100], ern_cluster);

% nonsocial-NFG
testing_meanAmplitude(char(grandAver), ...
    {'grandAVG_204_nonsoc_invis_NFG', 'grandAVG_211_nonsoc_vis_corr'}, ...
    {'Nonsoc_Invis_NFG', 'Nonsoc_Vis_Corr'}, ...
    'invisible_nonsoc_NFG_ERN_detection', [0 100], ern_cluster);

%% delta-ERN ANOVA (response type × social condition) → significant interaction (p = .018), significant ME for social (p = .032), no ME for response type
design_invis = table({'FE'; 'FE'; 'NFG'; 'NFG'}, ...
    {'social'; 'nonsocial'; 'social'; 'nonsocial'}, ...
    'VariableNames', {'ResponseType', 'SocialCondition'});
testing_meanAmplitude(char(diffWaves), ...
    {'diffWave_soc_invis_FE', 'diffWave_nonsoc_invis_FE', ...
     'diffWave_soc_invis_NFG', 'diffWave_nonsoc_invis_NFG'}, ...
    {'Soc_FE', 'Nonsoc_FE', 'Soc_NFG', 'Nonsoc_NFG'}, ...
    'invisible_deltaERN_ANOVA', [0 100], ern_cluster, ...
    'ranova', design_invis);

%% Pe - test if detectable
% social-FE
testing_meanAmplitude(char(grandAver), ...
    {'grandAVG_102_social_invis_FE', 'grandAVG_111_social_vis_corr'}, ...
    {'Soc_Invis_FE', 'Soc_Vis_Corr'}, ...
    'invisible_soc_FE_Pe_detection', [200 500], pe_cluster);

% social-NFG
testing_meanAmplitude(char(grandAver), ...
    {'grandAVG_104_social_invis_NFG', 'grandAVG_111_social_vis_corr'}, ...
    {'Soc_Invis_NFG', 'Soc_Vis_Corr'}, ...
    'invisible_soc_NFG_Pe_detection', [200 500], pe_cluster);

% nonsocial-FE
testing_meanAmplitude(char(grandAver), ...
    {'grandAVG_202_nonsoc_invis_FE', 'grandAVG_211_nonsoc_vis_corr'}, ...
    {'Nonsoc_Invis_FE', 'Nonsoc_Vis_Corr'}, ...
    'invisible_nonsoc_FE_Pe_detection', [200 500], pe_cluster);

% nonsocial-NFG
testing_meanAmplitude(char(grandAver), ...
    {'grandAVG_204_nonsoc_invis_NFG', 'grandAVG_211_nonsoc_vis_corr'}, ...
    {'Nonsoc_Invis_NFG', 'Nonsoc_Vis_Corr'}, ...
    'invisible_nonsoc_NFG_Pe_detection', [200 500], pe_cluster);

%% delta-Pe ANOVA (response type × social condition) → no significant interaction, significant ME for social (p = .025)
testing_meanAmplitude(char(diffWaves), ...
    {'diffWave_soc_invis_FE', 'diffWave_nonsoc_invis_FE', ...
     'diffWave_soc_invis_NFG', 'diffWave_nonsoc_invis_NFG'}, ...
    {'Soc_FE', 'Nonsoc_FE', 'Soc_NFG', 'Nonsoc_NFG'}, ...
    'invisible_deltaPe_ANOVA', [200 500], pe_cluster, ...
    'ranova', design_invis);

%% ========================================================================
%% CLEANUP & ORGANIZATION
%% ========================================================================
fprintf('\n=== Organizing Output Files ===\n');

% stop diary before moving files
diary off;

% move visible-target txt files
visFiles = dir('visible*.txt');
for i = 1:length(visFiles)
    movefile(visFiles(i).name, fullfile(visTableDir, visFiles(i).name));
end
fprintf('Moved %d visible-target statistics files\n', length(visFiles));

% move invisible-target txt files  
invisFiles = dir('invisible*.txt');
for i = 1:length(invisFiles)
    movefile(invisFiles(i).name, fullfile(invisTableDir, invisFiles(i).name));
end
fprintf('Moved %d invisible-target statistics files\n', length(invisFiles));

%% create summary file
summaryFile = fullfile(outputDir, 'analysis_summary.txt');
fid = fopen(summaryFile, 'w');
fprintf(fid, 'SocCEr ERP Analysis Summary\n');
fprintf(fid, '===========================\n\n');
fprintf(fid, 'Timestamp: %s\n', timestamp);
fprintf(fid, 'Script: batch_erp_analyses.m\n');
fprintf(fid, 'Author: Marlene Buch\n\n');
fprintf(fid, 'Output Structure:\n');
fprintf(fid, '  /tables/visible-target/   - %d statistics files\n', length(visFiles));
fprintf(fid, '  /tables/invisible-target/ - %d statistics files\n', length(invisFiles));
fprintf(fid, '  /logs/                    - analysis log\n');
fprintf(fid, '  /reports/                 - HTML report\n\n');
fprintf(fid, 'Electrode Clusters:\n');
fprintf(fid, '  ERN: [%s]\n', num2str(ern_cluster));
fprintf(fid, '  Pe:  [%s]\n', num2str(pe_cluster));
fclose(fid);

%% final output message
fprintf('\n========================================\n');
fprintf('Analysis Complete!\n');
fprintf('Output saved to:\n%s\n', outputDir);
fprintf('========================================\n');


% %% generate html report
% fprintf('\nGenerating HTML report...\n');
% publish('batch_erp_analyses.m', ...
%     'format', 'html', ...
%     'outputDir', reportsDir, ...
%     'evalCode', true);